### ISSUE TITLE
Mime Types Error

### ISSUE THREAD

**Issue by liorbrauer** [fredjean/middleman-s3_sync#110]
Hi,

I upgrade to version `3.3.4` and have gotten the following error when deploying:

```
/gems/fog-core-1.35.0/lib/fog/storage.rb:68:in `get_content_type': uninitialized constant Fog::Storage::MIME (NameError)
```

After a short investigation, I found that the `fog-core` dependency has been updated from `1.34.0` to `1.35.0`, which drops the required dependency on the `mime-types` gem. 

I manually added `mime-types` to my Gemfile and it works now. 

Might want to add this dependency directly to this gem?

**Comment by fredjean** [comment]
Could you paste the whole stack trace? I would like to see where the error occurs and I cannot reproduce locally. 

This might something that should probably be reported against Fog since other gems could be impacted.

**Comment by cmoel** [comment]
@liorbrauer I ran into the same issue but was able to fix it by adding the `mime-types` gem to my `Gemfile`:

```
gem "middleman-s3_sync", "~> 3.3.4"
gem "mime-types", "~> 3.0.0"
```

Does that resolve it for you?

**Comment by liorbrauer** [comment]
@cmoel Yeah, that's exactly what solved it for me, thanks for sharing as well.

@fredjean I recreated the error by removing the `mime-types` gem and trying to sync again:


```
/Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/fog-core-1.35.0/lib/fog/storage.rb:68:in `get_content_type': uninitialized constant Fog::Storage::MIME (NameError)
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/fog-core-1.35.0/lib/fog/storage.rb:79:in `parse_data'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/fog-aws-0.7.6/lib/fog/aws/requests/storage/put_object.rb:39:in `put_object'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/fog-aws-0.7.6/lib/fog/aws/models/storage/file.rb:212:in `save'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:65:in `block in update!'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:126:in `open'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:126:in `local_content'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:60:in `update!'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:152:in `block in update_resources'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:151:in `each'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:151:in `update_resources'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:42:in `sync'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.4/lib/middleman-s3_sync/commands.rb:59:in `s3_sync'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.6/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.6/lib/middleman-core/cli.rb:20:in `start'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.3.6/bin/middleman:18:in `<top (required)>'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `load'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `<main>'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/liorbrauer/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fredjean** [comment]
Thank you for the backtrace. I'll have time to look at it this afternoon.

**Comment by fredjean** [comment]
I have released v3.3.5 of the middleman-s3_sync gem. This adds a runtime dependency on the mime-types gem to work around the fog issue.

**Comment by liorbrauer** [comment]
Cool :+1:

**Comment by alex88** [comment]
@fredjean I've this in my gemfile lock:

```
middleman-s3_sync (3.3.6)
      ansi (~> 1.5.0)
      fog-aws (>= 0.7.0)
      map
      middleman-core (~> 3.3)
      mime-types (>= 3.0)
      parallel
      ruby-progressbar
      unf
```

but I still get the same stacktrace, any clue?

**Comment by alex88** [comment]
Nvm, my fault, had to clear cache on CI for some reason!

**Comment by fredjean** [comment]
No worries... Isn't cache invalidation one of the two hardest problems in CS? I'm glad you were able to resolve it.

**Comment by alex88** [comment]
Eheh :wink:

**Comment by monfresh** [comment]
Simply adding `mime-types` as a dependency of `middleman-s3_sync` does not solve the bug with Fog. This is because `mime-types` does not get automatically `require`d when added as a runtime dependency. However, if you manually add `gem 'mime-types'` to your Gemfile, Bundler will automatically `require` it, and syncing will work.

I just installed `middleman-s3_sync` version 3.3.7 (which includes `mime-types` — I verified its presence in my `Gemfile.lock`), and I can confirm that I got the `uninitialized constant Fog::Storage::MIME (NameError)` error when running `middleman s3_sync`.

When I added `gem 'mime-types'` to my Gemfile and ran `bundle install`, I was able to run `middleman s3_sync` without any issues. Then, I removed `mime-types` from my Gemfile, made a change to one of my site's files, and when I ran `middleman build` and `middleman s3_sync`, it failed again.

The solution is to make sure this issue gets fixed in Fog: https://github.com/fog/fog-core/issues/171

The workaround for this repo is to add a note to the README letting people know that if they run into that Fog issue, they will need to manually add the `mime-types` gem, and it can be removed as a dependency since it's not really a dependency for this repo.

**Comment by fredjean** [comment]
@monfresh Yes, I brought that very same point to the fog project a while back and was told to add `mime-types` to the dependency. Please, go make noise in the fog project and raise the issue to @geemus 's attention so it gets fixed where it needs to be fixed. I have already done what I could to mitigate the issues raised by the fog project's decision not to remove the dependency on `mime-types`.

@geemus, thank you for your work on fog, but this is causing some support issues with middleman-s3_sync that I will have to keep sending back your way. If there is a way to fix it on my side, by all means let me know. AFAIK, there are no fixes that I can apply further than adding the `mime-types` gem to my gemspec file. I would love to know of any other fixes otherwise.

**Comment by monfresh** [comment]
Thanks. I added my comments as well: https://github.com/fog/fog-core/issues/171#issuecomment-168907228

One thought: have you considered using the [aws-sdk](https://github.com/aws/aws-sdk-ruby) by itself, since this gem is specific to S3? What is the reason for depending on fog?

**Comment by fredjean** [comment]
The AWS SDK is rather painful to use. At the time, fog provided an awesome abstraction over it.

**Comment by monfresh** [comment]
Gotcha. I'm pretty sure that is no longer the case. If I found the time to replace fog with the official SDK, would you be open to a PR?

**Comment by fredjean** [comment]
Yes, I would.

**Comment by geemus** [comment]
I would also welcome help fixing it on the @fog side in case that would be faster/easier.

**Comment by monfresh** [comment]
To go back to this issue here, what I would do is remove the mime-types dependency (since it doesn't do anything to solve the problem), and update the gemspec to lock the version of fog-core to 1.34.0 until fog-core fixes this issue. That way, middleman-s3_sync users won't run into this issue while we're waiting for fog-core to be fixed.
